# Generated by Django 5.2.8 on 2026-02-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_visits_alter_category_id_alter_customuser_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
