# Generated by Django 5.2.8 on 2026-02-22 04:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
