# Generated by Django 5.2.8 on 2026-04-06 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userpayment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
    ]
