# Generated by Django 5.2.8 on 2026-04-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='kashier_order_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='kashier_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
