# Generated by Cursor on 2026-04-08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_userpayment_amount_userpayment_kashier_order_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PdfExportJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("queued", "Queued"), ("running", "Running"), ("succeeded", "Succeeded"), ("failed", "Failed")], default="queued", max_length=20)),
                ("source_hash", models.CharField(db_index=True, max_length=64)),
                ("pdf_file", models.FileField(blank=True, null=True, upload_to="exports/pdfs/")),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pdf_exports", to="core.customuser")),
            ],
        ),
    ]

