# Generated by Django 5.2.8 on 2026-04-09 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_category_id_alter_customuser_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='discount_code_used',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percentage', models.PositiveIntegerField(default=0, help_text='Percentage discount (0-100)')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this coupon has been used successfully')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(help_text='The user who owns/generated this coupon', on_delete=django.db.models.deletion.CASCADE, related_name='owned_coupons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
