# Generated by Django 5.2.8 on 2026-04-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userpayment_discount_code_used_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='contact_link',
            field=models.URLField(blank=True, help_text="Custom CTA link for 'Get In Touch' buttons", max_length=500, null=True),
        ),
    ]
