# Generated by Django 5.2.8 on 2026-04-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_personalinfo_contact_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='video_type',
            field=models.CharField(choices=[('long', 'Long Video'), ('reel', 'Short/Reel')], default='long', max_length=10),
        ),
    ]
