# Generated by Django 5.2.8 on 2026-04-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_project_slug_project_video_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='contact_link',
        ),
    ]
