# Generated by Django 5.2.8 on 2026-04-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_personalinfo_contact_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='booking_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
