# Generated by Django 5.2.8 on 2026-04-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_personalinfo_booking_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
