# Generated by Django 5.2.8 on 2026-04-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_manualpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='manualpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('needs_review', 'Needs Manual Review')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='booking_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
