# Generated by Django 5.2.8 on 2026-04-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_link_url_alter_manualpayment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_discount_percentage', models.PositiveIntegerField(default=25, help_text='Discount percentage to show in the dashboard banner.')),
                ('banner_coupon_code', models.CharField(default='SKILLIFLY2026', help_text='Coupon code to show in the banner.', max_length=50)),
                ('banner_is_active', models.BooleanField(default=True, help_text='Whether the payment banner is enabled globally.')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
