# Generated by Django 5.2.8 on 2026-04-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=254)),
                ('user_title', models.CharField(blank=True, help_text='e.g. Video Editor, Frontend Developer', max_length=254, null=True)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='reviews/')),
                ('content', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5, help_text='1 to 5 stars')),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
