# Generated by Django 5.2.8 on 2026-04-28 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional custom title for the showcase', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Short description of the user or their work')),
                ('preview_image', models.ImageField(blank=True, help_text='Custom preview image (defaults to profile pic if empty)', null=True, upload_to='showcase/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='showcase', to='core.profile')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
