# Generated by Django 5.2.8 on 2026-04-30 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_showcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Custom browser title tag', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Custom meta description for search engines', null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500, null=True)),
                ('og_title', models.CharField(blank=True, help_text='Title for social media sharing', max_length=255, null=True)),
                ('og_description', models.TextField(blank=True, help_text='Description for social media sharing', null=True)),
                ('og_image', models.ImageField(blank=True, help_text='Custom image for social media sharing', null=True, upload_to='seo_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
