# Generated by Django 5.2.8 on 2026-05-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_analyticsvisit_analyticsevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdomain',
            name='dns_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
