# Generated by Django 5.2.8 on 2026-05-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_collaborator_delete_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
