# Generated by Django 5.2.8 on 2026-05-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_collaborator_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
