# Generated by Django 5.2.8 on 2026-05-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_creator_projectcategory_project_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='url',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='picture',
        ),
        migrations.AlterField(
            model_name='creator',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='ProjectCategory',
        ),
    ]
