# Generated by Django 5.2.8 on 2026-05-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_project_category_remove_creator_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
