# Generated by Django 5.2.8 on 2026-05-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_affiliateprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('', 'No Category'), ('commercial', 'Commercial'), ('music_video', 'Music Video'), ('documentary', 'Documentary'), ('short_film', 'Short Film'), ('wedding', 'Wedding'), ('corporate', 'Corporate'), ('social_media', 'Social Media'), ('travel', 'Travel'), ('fashion', 'Fashion'), ('other', 'Other')], default='', help_text='Content category for portfolio filtering', max_length=20),
        ),
    ]
