# Generated by Django 5.2.8 on 2026-05-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_projectcategory_alter_project_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of appearance on landing page'),
        ),
    ]
