# Generated by Django 5.2.8 on 2026-07-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_fix_customdomain_domain_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='kashier_order_id',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='kashier_session_id',
        ),
        migrations.AddField(
            model_name='userpayment',
            name='fawaterk_intent_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
