# Generated by Django 5.2.8 on 2026-08-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('editor', 'Editor'), ('client', 'Client')], default='editor', help_text='editor = builds a portfolio, client = hires editors', max_length=10),
        ),
    ]
