# Generated by Django 5.2.8 on 2026-08-05 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_user_account(apps, schema_editor):
    """Carry each user's account_type over to the new UserAccount table before dropping the column."""
    CustomUser = apps.get_model('core', 'CustomUser')
    UserAccount = apps.get_model('core', 'UserAccount')
    for user in CustomUser.objects.all().iterator():
        account_type = getattr(user, 'account_type', None) or 'editor'
        if account_type not in ('editor', 'client'):
            account_type = 'editor'
        UserAccount.objects.create(user=user, account_type=account_type)


def restore_user_account(apps, schema_editor):
    """Reverse: write UserAccount.account_type back onto CustomUser (field is re-added by then)."""
    CustomUser = apps.get_model('core', 'CustomUser')
    UserAccount = apps.get_model('core', 'UserAccount')
    for ua in UserAccount.objects.all().iterator():
        CustomUser.objects.filter(pk=ua.user_id).update(account_type=ua.account_type)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_customuser_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('editor', 'Editor'), ('client', 'Client')], default='editor', help_text='editor = builds a portfolio, client = hires editors', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Account',
                'verbose_name_plural': 'User Accounts',
            },
        ),
        migrations.RunPython(backfill_user_account, restore_user_account),
        migrations.RemoveField(
            model_name='customuser',
            name='account_type',
        ),
    ]
