# Generated by Django 5.2.8 on 2026-08-06 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_website_reviews(apps, schema_editor):
    Review = apps.get_model('core', 'Review')
    WebsiteReview = apps.get_model('core', 'WebsiteReview')
    if WebsiteReview.objects.exists():
        return
    records = []
    for r in Review.objects.filter(user__isnull=True):
        records.append(WebsiteReview(
            reviewer_id=r.reviewer_id,
            user_name=r.user_name,
            user_title=r.user_title,
            user_image=r.user_image.name if r.user_image else None,
            content=r.content,
            rating=r.rating,
            is_featured=r.is_featured,
            order=r.order,
            created_at=r.created_at,
        ))
    WebsiteReview.objects.bulk_create(records)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_review_reviewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=254)),
                ('user_title', models.CharField(blank=True, help_text='e.g. Video Editor, Frontend Developer', max_length=254, null=True)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='reviews/')),
                ('content', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5, help_text='1 to 5 stars')),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance on landing page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(blank=True, help_text='The authenticated user who submitted this review (null = admin/manual)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.RunPython(copy_website_reviews, migrations.RunPython.noop),
    ]
