# Generated by Django 5.2.8 on 2026-08-13 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_split_client_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientreview',
            name='rating',
            field=models.PositiveIntegerField(default=5, help_text='1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(default=5, help_text='1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
