# Generated by Django 5.2.8 on 2026-08-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_clientreview_rating_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='schools/')),
                ('discount_code', models.CharField(max_length=50, unique=True)),
                ('number_of_students', models.PositiveIntegerField(default=0, help_text='Number of students at the school')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
            },
        ),
    ]
