# Generated by Django 5.2.8 on 2026-08-16 08:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL slug, e.g. serb-skool', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='tagline',
            field=models.CharField(blank=True, help_text='Short tagline shown under the school name', max_length=300),
        ),
        migrations.AlterField(
            model_name='school',
            name='number_of_students',
            field=models.PositiveIntegerField(default=0, help_text='Fallback count; live stats are computed from Student records'),
        ),
        migrations.CreateModel(
            name='SchoolStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('specialty', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('avatar_color', models.CharField(default='#1D4ED8', help_text='Gradient start hex for the avatar', max_length=9)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden cards are revealed by the Show More button')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.school')),
            ],
            options={
                'verbose_name': 'School Student',
                'verbose_name_plural': 'School Students',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SchoolStudentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.schoolstudent')),
            ],
            options={
                'verbose_name': 'School Student Rating',
                'verbose_name_plural': 'School Student Ratings',
            },
        ),
        migrations.CreateModel(
            name='SchoolVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#1D4ED8', help_text='Gradient start hex for the thumbnail', max_length=9)),
                ('duration', models.CharField(default='2:41', max_length=20)),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='core.schoolstudent')),
            ],
            options={
                'verbose_name': 'School Video',
                'verbose_name_plural': 'School Videos',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SchoolVideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=80)),
                ('author_color', models.CharField(default='#6D28D9', max_length=9)),
                ('body', models.TextField()),
                ('stars', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.schoolvideo')),
            ],
            options={
                'verbose_name': 'School Video Comment',
                'verbose_name_plural': 'School Video Comments',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SchoolVideoRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.schoolvideo')),
            ],
            options={
                'verbose_name': 'School Video Rating',
                'verbose_name_plural': 'School Video Ratings',
            },
        ),
    ]
