# Generated by Django 5.2.8 on 2026-08-16 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_school_slug_school_tagline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolvideo',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='schoolvideo',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='schoolvideo',
            name='views',
        ),
    ]
