# Generated by Django 5.2.8 on 2026-08-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_schoolstudent_user_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolstudent',
            name='avatar_color',
        ),
        migrations.RemoveField(
            model_name='schoolstudent',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='schoolstudent',
            name='name',
        ),
        migrations.RemoveField(
            model_name='schoolstudent',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='schoolstudent',
            name='specialty',
        ),
    ]
