# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_remove_schoolstudent_denormalized_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='media_height',
            field=models.PositiveIntegerField(blank=True, help_text='True video height in px (probed, used to size the player box)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='media_width',
            field=models.PositiveIntegerField(blank=True, help_text='True video width in px (probed, used to size the player box)', null=True),
        ),
    ]
