# Generated by Django 5.2.8 on 2026-08-16 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_project_media_dims'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolvideorating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_video_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='schoolvideorating',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('project', 'user'), name='uniq_video_rating_per_user'),
        ),
    ]
