# Generated by Django 5.2.8 on 2026-08-18 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_add_user_to_schoolvideorating'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Set only for school_admin accounts — the school this user manages', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='core.school'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='account_type',
            field=models.CharField(choices=[('editor', 'Editor'), ('client', 'Client'), ('school_admin', 'School Admin')], default='editor', help_text='editor = builds a portfolio, client = hires editors, school_admin = manages a school', max_length=15),
        ),
    ]
