# Generated by Django 5.2.8 on 2026-08-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_repair_userpayment_kashier_columns'),
        ('core', '0061_add_school_admin_account_type'),
    ]

    operations = [
    ]
