# Generated by Django 5.2.8 on 2026-08-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_merge_20260821_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='section_order',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of section keys for portfolio display'),
        ),
    ]
