# Generated by Django 5.2.8 on 2026-08-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_alter_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualpayment',
            name='sender_identifier',
            field=models.CharField(max_length=500),
        ),
    ]
