# Generated by Django 5.2.8 on 2026-08-29 01:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_alter_manualpayment_sender_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='showcase_auto_rotate',
            field=models.BooleanField(default=True, help_text='Automatically rotate through the shown themes until a visitor interacts.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='showcase_default_theme',
            field=models.CharField(blank=True, default='', help_text='Theme slug loaded first in the hero showcase (must be one of showcase_themes).', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='showcase_overrides',
            field=models.JSONField(blank=True, default=dict, help_text="Map of theme slug to a username whose portfolio is pinned for that tab ('' or missing = auto-pick the best available)."),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='showcase_themes',
            field=models.JSONField(blank=True, default=list, help_text="Ordered list of theme slugs shown as tabs on the landing page, e.g. ['creative_white','animated_dark','monochrome','categories']."),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='showcase_zoom',
            field=models.PositiveIntegerField(default=50, help_text='Zoom % of the embedded portfolio preview (100 = full size, 50 = zoomed out to half).', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='manualpayment',
            name='sender_identifier',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
