# Generated by Django 5.2.8 on 2026-09-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_alter_manualpayment_sender_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconversation',
            name='workflow_state',
            field=models.JSONField(blank=True, help_text='Active guided AI workflow state (e.g. add_project, change_theme, bio wizard)', null=True),
        ),
    ]
