# Generated by Django 5.2.8 on 2026-09-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_agentconversation_workflow_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['order', '-start_date', '-id']},
        ),
        migrations.AddField(
            model_name='experience',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='agentconversation',
            name='title',
            field=models.CharField(default='Skillifly AI', max_length=255),
        ),
    ]
