# Generated by Django 5.2.8 on 2026-09-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_experience_options_experience_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmessage',
            name='user_rating',
            field=models.CharField(blank=True, choices=[('up', 'Thumbs up'), ('down', 'Thumbs down')], help_text='User feedback on this agent response (feedback loop for quality tuning)', max_length=10, null=True),
        ),
    ]
