# Generated by Django 5.2.8 on 2026-09-22 11:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_remove_pdfexportjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCustomDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('card_design', models.CharField(choices=[('minimal', 'Minimal Grid'), ('showcase', 'Showcase Masonry'), ('timeline', 'Timeline List')], default='minimal', max_length=20)),
                ('section_1_title', models.CharField(default='Featured Work', max_length=60)),
                ('section_2_title', models.CharField(default='All Projects', max_length=60)),
                ('section_3_title', models.CharField(default='About', max_length=60)),
                ('primary_font', models.CharField(choices=[('Inter', 'Inter'), ('Cairo', 'Cairo'), ('Almarai', 'Almarai'), ('Tajawal', 'Tajawal'), ('Noto Kufi Arabic', 'Noto Kufi Arabic'), ('IBM Plex Sans Arabic', 'IBM Plex Sans Arabic'), ('Noto Sans Arabic', 'Noto Sans Arabic'), ('Amiri', 'Amiri'), ('Readex Pro', 'Readex Pro'), ('El Messiri', 'El Messiri'), ('Changa', 'Changa'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Montserrat', 'Montserrat'), ('Poppins', 'Poppins'), ('Raleway', 'Raleway'), ('Work Sans', 'Work Sans'), ('DM Sans', 'DM Sans'), ('Space Grotesk', 'Space Grotesk'), ('Syne', 'Syne'), ('Manrope', 'Manrope'), ('Nunito', 'Nunito'), ('Source Sans 3', 'Source Sans 3'), ('Playfair Display', 'Playfair Display')], default='Inter', max_length=60)),
                ('secondary_font', models.CharField(choices=[('Inter', 'Inter'), ('Cairo', 'Cairo'), ('Almarai', 'Almarai'), ('Tajawal', 'Tajawal'), ('Noto Kufi Arabic', 'Noto Kufi Arabic'), ('IBM Plex Sans Arabic', 'IBM Plex Sans Arabic'), ('Noto Sans Arabic', 'Noto Sans Arabic'), ('Amiri', 'Amiri'), ('Readex Pro', 'Readex Pro'), ('El Messiri', 'El Messiri'), ('Changa', 'Changa'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Montserrat', 'Montserrat'), ('Poppins', 'Poppins'), ('Raleway', 'Raleway'), ('Work Sans', 'Work Sans'), ('DM Sans', 'DM Sans'), ('Space Grotesk', 'Space Grotesk'), ('Syne', 'Syne'), ('Manrope', 'Manrope'), ('Nunito', 'Nunito'), ('Source Sans 3', 'Source Sans 3'), ('Playfair Display', 'Playfair Display')], default='Cairo', max_length=60)),
                ('background_type', models.CharField(choices=[('solid', 'Solid'), ('gradient', 'Gradient')], default='solid', max_length=10)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a 6-digit hex color, e.g. #FFFFFF.')])),
                ('gradient_start', models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a 6-digit hex color, e.g. #FFFFFF.')])),
                ('gradient_end', models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a 6-digit hex color, e.g. #FFFFFF.')])),
                ('gradient_angle', models.PositiveSmallIntegerField(default=135, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)])),
                ('primary_font_color', models.CharField(default='#111111', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a 6-digit hex color, e.g. #FFFFFF.')])),
                ('secondary_font_color', models.CharField(default='#5B5B5B', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a 6-digit hex color, e.g. #FFFFFF.')])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_design', to='core.profile')),
            ],
            options={
                'verbose_name': 'Custom Design',
                'verbose_name_plural': 'Custom Designs',
            },
        ),
    ]
