# Generated by Django 5.2.8 on 2026-09-22 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_portfolio_custom_design'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliocustomdesign',
            name='background_type',
        ),
        migrations.RemoveField(
            model_name='portfoliocustomdesign',
            name='card_design',
        ),
        migrations.RemoveField(
            model_name='portfoliocustomdesign',
            name='gradient_angle',
        ),
        migrations.RemoveField(
            model_name='portfoliocustomdesign',
            name='gradient_end',
        ),
        migrations.RemoveField(
            model_name='portfoliocustomdesign',
            name='gradient_start',
        ),
        migrations.RemoveField(
            model_name='portfoliocustomdesign',
            name='primary_font',
        ),
        migrations.RemoveField(
            model_name='portfoliocustomdesign',
            name='primary_font_color',
        ),
        migrations.RemoveField(
            model_name='portfoliocustomdesign',
            name='secondary_font',
        ),
        migrations.RemoveField(
            model_name='portfoliocustomdesign',
            name='secondary_font_color',
        ),
        migrations.RemoveField(
            model_name='portfoliocustomdesign',
            name='section_1_title',
        ),
        migrations.RemoveField(
            model_name='portfoliocustomdesign',
            name='section_2_title',
        ),
        migrations.RemoveField(
            model_name='portfoliocustomdesign',
            name='section_3_title',
        ),
        migrations.AddField(
            model_name='portfoliocustomdesign',
            name='creators_title',
            field=models.CharField(default='Creators I Worked With', max_length=60),
        ),
        migrations.AddField(
            model_name='portfoliocustomdesign',
            name='education_title',
            field=models.CharField(default='Education', max_length=60),
        ),
        migrations.AddField(
            model_name='portfoliocustomdesign',
            name='experience_title',
            field=models.CharField(default='Experience', max_length=60),
        ),
        migrations.AddField(
            model_name='portfoliocustomdesign',
            name='projects_title',
            field=models.CharField(default='Selected Works', max_length=60),
        ),
        migrations.AddField(
            model_name='portfoliocustomdesign',
            name='reviews_title',
            field=models.CharField(default='Client Reviews', max_length=60),
        ),
        migrations.AddField(
            model_name='portfoliocustomdesign',
            name='skills_title',
            field=models.CharField(default='Software & Skills', max_length=60),
        ),
        migrations.AddField(
            model_name='portfoliocustomdesign',
            name='surface_color',
            field=models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a 6-digit hex color, e.g. #FFFFFF.')]),
        ),
        migrations.AlterField(
            model_name='portfoliocustomdesign',
            name='background_color',
            field=models.CharField(default='#F3F7FA', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a 6-digit hex color, e.g. #FFFFFF.')]),
        ),
    ]
