# Generated by Django 5.2.8 on 2026-09-22 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_remove_portfoliocustomdesign_background_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioCustomDesign',
        ),
    ]
