# Generated by Django 5.2.8 on 2026-09-23 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_delete_portfoliocustomdesign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Order of appearance on the portfolio'),
        ),
    ]
