# Generated by Django 5.2.8 on 2026-09-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_project_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='section_names',
            field=models.JSONField(blank=True, default=dict, help_text='Map of section key -> custom display name(s) shown on the portfolio'),
        ),
    ]
