# Generated by Django 5.2.8 on 2026-09-26 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_paymenttrackingevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='storage_addon_bytes',
            field=models.BigIntegerField(default=0, help_text='Extra video storage in bytes granted by purchased storage add-ons.'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudflare_uid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Upload'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('playback_hls_url', models.URLField(blank=True, max_length=500)),
                ('playback_dash_url', models.URLField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
