# Generated by Django 5.2.8 on 2026-09-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_profile_storage_addon_bytes_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme_settings',
            field=models.JSONField(blank=True, default=dict, help_text="Per-theme appearance overrides, e.g. {'background': '#0A0E27'}. Only honoured by themes listed in core.theme_colors.BACKGROUND_ENABLED_THEMES."),
        ),
    ]
