from django.urls import path, include
from core import views
from builder import views as builder_views

urlpatterns = [
    path('', views.index, name='index'),
    path('ar/', views.arabic_landing_view, name='arabic_landing'),
    path('signup/', views.editor_signup_view, name='signup'),
    path('ar/signup/', views.arabic_editor_signup_view, name='arabic_signup'),
    path('signup/editor/', views.editor_signup_view, name='editor_signup'),
    path('ar/signup/editor/', views.arabic_editor_signup_view, name='arabic_editor_signup'),
    path('signup/client/', views.client_signup_view, name='client_signup'),
    path('ar/signup/client/', views.arabic_client_signup_view, name='arabic_client_signup'),
    path('signup/school-admin/', views.school_admin_signup_view, name='school_admin_signup'),
    path('ar/signup/school-admin/', views.arabic_school_admin_signup_view, name='arabic_school_admin_signup'),
    path('signup/school-admin/choose-school/', views.school_admin_choose_school_view, name='school_admin_choose_school'),
    path('ar/signup/school-admin/choose-school/', views.arabic_school_admin_choose_school_view, name='arabic_school_admin_choose_school'),
    path('verify-email/', views.verify_otp_view, name='verify_otp'),
    path('resend-otp/', views.resend_otp_view, name='resend_otp'),
    path('signin/', views.signin_view, name='signin'),
    path('ar/signin/', views.arabic_signin_view, name='arabic_signin'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('ar/dashboard/', views.arabic_dashboard_view, name='arabic_dashboard'),
    path('ar/builder/', builder_views.arabic_builder_view, name='arabic_builder'),
    path('client_dashboard/', views.client_dashboard_view, name='client_dashboard'),
    path('ar/client_dashboard/', views.arabic_client_dashboard_view, name='arabic_client_dashboard'),
    path('school_admin_dashboard/', views.school_admin_dashboard_view, name='school_admin_dashboard'),
    path('ar/school_admin_dashboard/', views.arabic_school_admin_dashboard_view, name='arabic_school_admin_dashboard'),
    path('my-school-stats/', views.my_school_stats_view, name='my_school_stats'),
    path('ar/my-school-stats/', views.arabic_my_school_stats_view, name='arabic_my_school_stats'),
    path('client_reviews/', views.client_reviews_view, name='client_reviews'),
    path('ar/client_reviews/', views.arabic_client_reviews_view, name='arabic_client_reviews'),
    path('dashboard/reviews/', views.reviews_management_view, name='reviews_management'),
    path('ar/dashboard/reviews/', views.arabic_reviews_management_view, name='arabic_reviews_management'),
    path('dashboard/reviews/<int:review_id>/toggle/', views.toggle_review_featured_view, name='toggle_review_featured'),
    path('dashboard/reviews/<int:review_id>/avatar/', views.update_review_avatar_view, name='update_review_avatar'),
    path('profile/', views.profile_view, name='profile'),
    path('ar/profile/', views.arabic_profile_view, name='arabic_profile'),
    path('themes/', views.themes, name='themes'),
    path('ar/themes/', views.arabic_themes, name='arabic_themes'),
    path('ar/update/', builder_views.arabic_update_portfolio_view, name='arabic_update_portfolio'),
    path('dashboard/seo/', views.seo_settings_view, name='seo_settings'),
    path('ar/dashboard/seo/', views.arabic_seo_settings_view, name='arabic_seo_settings'),
    path('dashboard/domain/', views.custom_domain_view, name='custom_domain'),
    path('ar/dashboard/domain/', views.arabic_custom_domain_view, name='arabic_custom_domain'),
    path('dashboard/customize/', views.customize_theme_view, name='customize_theme'),
    path('ar/dashboard/customize/', views.arabic_customize_theme_view, name='arabic_customize_theme'),
    path('dashboard/customize/sections-names/', views.customize_section_names_view, name='customize_section_names'),
    path('ar/dashboard/customize/sections-names/', views.arabic_customize_section_names_view, name='arabic_customize_section_names'),
    path('dashboard/customize/experiences/', views.customize_experience_order_view, name='customize_experience_order'),
    path('ar/dashboard/customize/experiences/', views.arabic_customize_experience_order_view, name='arabic_customize_experience_order'),
    path('dashboard/customize/experiences/save/', views.customize_experience_order_save, name='customize_experience_order_save'),
    path('dashboard/customize/projects/', views.customize_project_order_view, name='customize_project_order'),
    path('ar/dashboard/customize/projects/', views.arabic_customize_project_order_view, name='arabic_customize_project_order'),
    path('dashboard/customize/projects/save/', views.customize_project_order_save, name='customize_project_order_save'),

    # Video uploads — Cloudflare Stream, direct-to-provider via tus
    path('dashboard/videos/upload/', views.upload_video_view, name='upload_video'),
    path('ar/dashboard/videos/upload/', views.arabic_upload_video_view, name='arabic_upload_video'),
    path('videos/create-upload/', views.create_video_upload, name='create_video_upload'),
    path('videos/<int:video_id>/status/', views.video_status, name='video_status'),
    path('videos/<int:video_id>/cancel/', views.cancel_video_upload, name='cancel_video_upload'),
    path('videos/webhooks/cloudflare-stream/', views.cloudflare_stream_webhook, name='cloudflare_stream_webhook'),

    path('logout/', views.logout_view, name='logout'),
    path('toggle-visibility/', views.activate_portfolio, name='activate_portfolio'),
    path('sitemap.xml', views.sitemap_view, name='sitemap'),
    path('robots.txt', views.robots_txt_view, name='robots_txt'),
    path('llms.txt', views.llms_txt_view, name='llms_txt'),
    path('terms/', views.terms_view, name='terms'),
    path('privacy/', views.privacy_view, name='privacy'),
    path('contact/', views.contact_view, name='contact'),
    path('sw.js', views.service_worker, name='service_worker'),
    path('image-thumb/<path:name>/<int:size>/', views.image_thumb, name='image_thumb'),
    path('submit-review-exclusive/', views.submit_review_view, name='submit_review'),
    path('review/<str:username>/', views.client_review_view, name='client_review'),
    path('ar/review/<str:username>/', views.arabic_client_review_view, name='arabic_client_review'),
    path('revenue-report-exclusive/', views.revenue_report, name='revenue_report'),
    path('admin-dashboard-exclusive/', views.admin_dashboard, name='admin_dashboard'),
    
    # Management - Move more specific ones UP
    path('manage/affiliates/', views.manage_affiliates, name='manage_affiliates'),
    path('manage/showcase/update/', views.manage_showcase_update, name='manage_showcase_update'),
    path('manage/showcase/entry/add/', views.manage_showcase_entry_add, name='manage_showcase_entry_add'),
    path('manage/showcase/entry/toggle/<int:pk>/', views.manage_showcase_entry_toggle, name='manage_showcase_entry_toggle'),
    path('manage/showcase/entry/move/<int:pk>/<str:direction>/', views.manage_showcase_entry_move, name='manage_showcase_entry_move'),
    path('manage/showcase/entry/delete/<int:pk>/', views.manage_showcase_entry_delete, name='manage_showcase_entry_delete'),
    path('manage/blog/', include('blog.dashboard_urls')),
    path('manage/experiences/', views.manage_experience_order, name='manage_experience_order'),
    path('manage/experiences/save/', views.manage_experience_order_save, name='manage_experience_order_save'),
    path('manage/payment-tracking/', views.manage_payment_tracking, name='manage_payment_tracking'),
    path('manage/', views.manage_dashboard, name='manage_dashboard'),
    path('affiliate/', views.affiliate_view, name='affiliate'),
    path('affiliate/join/', views.join_affiliate, name='join_affiliate'),
]
