from django.urls import path, include
from core import views

urlpatterns = [
    path('', views.index, name='index'),
    path('ar/', views.arabic_landing_view, name='arabic_landing'),
    path('signup/', views.signup_view, name='signup'),
    path('ar/signup/', views.arabic_signup_view, name='arabic_signup'),
    path('verify-email/', views.verify_otp_view, name='verify_otp'),
    path('resend-otp/', views.resend_otp_view, name='resend_otp'),
    path('signin/', views.signin_view, name='signin'),
    path('ar/signin/', views.arabic_signin_view, name='arabic_signin'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('ar/dashboard/', views.arabic_dashboard_view, name='arabic_dashboard'),
    path('profile/', views.profile_view, name='profile'),
    path('ar/profile/', views.arabic_profile_view, name='arabic_profile'),
    path('themes/', views.themes, name='themes'),
    path('ar/themes/', views.arabic_themes, name='arabic_themes'),
    path('ar/update/', views.arabic_update_portfolio_view, name='arabic_update_portfolio'),
    path('dashboard/seo/', views.seo_settings_view, name='seo_settings'),
    path('ar/dashboard/seo/', views.arabic_seo_settings_view, name='arabic_seo_settings'),
    path('dashboard/domain/', views.custom_domain_view, name='custom_domain'),
    path('ar/dashboard/domain/', views.arabic_custom_domain_view, name='arabic_custom_domain'),

    path('logout/', views.logout_view, name='logout'),
    path('toggle-visibility/', views.activate_portfolio, name='activate_portfolio'),
    path('sitemap.xml', views.sitemap_view, name='sitemap'),
    path('robots.txt', views.robots_txt_view, name='robots_txt'),
    path('export/pdf/start/', views.export_pdf_start, name='export_pdf_start'),
    path('export/pdf/status/<int:job_id>/', views.export_pdf_status, name='export_pdf_status'),
    path('export/pdf/download/<int:job_id>/', views.export_pdf_download, name='export_pdf_download'),
    path('terms/', views.terms_view, name='terms'),
    path('privacy/', views.privacy_view, name='privacy'),
    path('contact/', views.contact_view, name='contact'),
    path('sw.js', views.service_worker, name='service_worker'),
    path('submit-review-exclusive/', views.submit_review_view, name='submit_review'),
    path('revenue-report-exclusive/', views.revenue_report, name='revenue_report'),
    path('admin-dashboard-exclusive/', views.admin_dashboard, name='admin_dashboard'),
    
    # Management - Move more specific ones UP
    path('manage/affiliates/', views.manage_affiliates, name='manage_affiliates'),
    path('manage/blog/', include('blog.dashboard_urls')),
    path('manage/', views.manage_dashboard, name='manage_dashboard'),
    path('affiliate/', views.affiliate_view, name='affiliate'),
    path('affiliate/join/', views.join_affiliate, name='join_affiliate'),
]
