# Generated by Django 5.2.8 on 2026-05-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Override the canonical URL if this content exists elsewhere'),
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for featured image (important for SEO)', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'العربية')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Max 160 characters for best SEO results', max_length=160),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True),
        ),
    ]
